"""empty message

Revision ID: 6078f9507913
Revises: b74a24e82c88
Create Date: 2020-10-29 09:45:50.454395

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '6078f9507913'
down_revision = 'b74a24e82c88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('altitude', sa.Float(), nullable=True))
    op.add_column('schedule', sa.Column('slope', sa.Float(), nullable=True))
    op.add_column('schedule', sa.Column('spacing', sa.Float(), nullable=True))
    op.add_column('schedule', sa.Column('speed', sa.Float(), nullable=True))
    op.alter_column('schedule', 'status',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.add_column('survey_parameters', sa.Column('farm_id', sa.Integer(), nullable=False))
    op.alter_column('survey_parameters', 'altitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('survey_parameters', 'slope',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('survey_parameters', 'spacing',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.alter_column('survey_parameters', 'speed',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=True)
    op.create_foreign_key(None, 'survey_parameters', 'farm', ['farm_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'survey_parameters', type_='foreignkey')
    op.alter_column('survey_parameters', 'speed',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('survey_parameters', 'spacing',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('survey_parameters', 'slope',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.alter_column('survey_parameters', 'altitude',
               existing_type=postgresql.DOUBLE_PRECISION(precision=53),
               nullable=False)
    op.drop_column('survey_parameters', 'farm_id')
    op.alter_column('schedule', 'status',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_column('schedule', 'speed')
    op.drop_column('schedule', 'spacing')
    op.drop_column('schedule', 'slope')
    op.drop_column('schedule', 'altitude')
    # ### end Alembic commands ###
