"""empty message

Revision ID: 6d8f2f9fa925
Revises: a74eebe2a599
Create Date: 2020-10-18 16:46:50.069735

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d8f2f9fa925'
down_revision = 'a74eebe2a599'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collected_image', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collected_image', 'status')
    # ### end Alembic commands ###
