"""empty message

Revision ID: a74eebe2a599
Revises: f67c093aca2c
Create Date: 2020-10-18 11:55:21.410203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a74eebe2a599'
down_revision = 'f67c093aca2c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collected_image',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('details', sa.String(length=1000), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('image', sa.String(length=1000), nullable=True),
    sa.Column('drone_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['drone_id'], ['drone.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('collected_image')
    # ### end Alembic commands ###
