"""empty message

Revision ID: f67c093aca2c
Revises: 9e2cb2f2fb38
Create Date: 2020-10-17 19:23:31.678283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f67c093aca2c'
down_revision = '9e2cb2f2fb38'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('schedule', sa.Column('status', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('schedule', 'status')
    # ### end Alembic commands ###
